// #region ── Objets spatiaux ───────────────────────────────────────────────────

// Source de vérité unique pour toutes les données 3D et UI des objets du système solaire.
// Importé par main.js (construction de la scène) et ui.js (sidebar, tooltip).
export const OBJECTS = [
  {
    // ── Identification ──
    id: "sun",
    name: "Soleil",
    type: "star",
    // ── UI ──
    color: "#F9CB42",
    desc: "Notre étoile, âgée de 4,6 milliards d'années. Elle représente 99,8 % de la masse du système solaire.",
    facts: {
      distance: "Centre",
      rayon: "696 340 km",
      type: "Naine jaune (G2V)",
    },
    // ── 3D ──
    radius: 2.5,
    texturePath: "/textures/8k_sun.jpg",
    emissive: true,
    rotSpeed: 0.037,
    atmosphere: null,
    sim: {
      taille:
        "Fortement réduite pour la lisibilité (réel : 109× le diamètre terrestre)",
    },
    wikipedia: "https://fr.wikipedia.org/wiki/Soleil",
  },
  {
    id: "mercury",
    name: "Mercure",
    type: "planet",
    color: "#b4b2a9",
    desc: "La plus petite planète du système solaire. Sans atmosphère protectrice, les températures varient de -180°C à 430°C.",
    facts: {
      distance: "77M km du Soleil",
      rayon: "2 439 km",
      orbite: "88 jours",
    },
    radius: 0.25,
    texturePath: "/textures/8k_mercury.jpg",
    roughness: 1,
    orbitR: 8,
    orbitColor: [0.5, 0.45, 0.4],
    speed: 1.62,
    speedKms: 47.4,
    rotSpeed: 0.017,
    inclination: 7.0,
    axialTilt: 0.03,
    atmosphere: null,
    wikipedia: "https://fr.wikipedia.org/wiki/Mercure_(plan%C3%A8te)",
  },
  {
    id: "venus",
    name: "Vénus",
    type: "planet",
    color: "#F0997B",
    desc: "La planète la plus chaude (465°C). Tourne à l'envers et une journée vénusienne dure plus longtemps qu'une année.",
    facts: {
      distance: "108M km du Soleil",
      rayon: "6 051 km",
      orbite: "225 jours",
    },
    radius: 0.48,
    texturePath: "/textures/8k_venus_surface.jpg",
    roughness: 0.95,
    orbitR: 12,
    orbitColor: [0.9, 0.75, 0.4],
    speed: 0.79,
    speedKms: 35.0,
    rotSpeed: -0.004,
    inclination: 3.4,
    axialTilt: 177.4,
    atmosphere: { color: "255,200,100", size: 1.8 },
    clouds: {
      texture: "/textures/4k_venus_atmosphere.jpg",
      opacity: 0.5,
      speed: -0.3,
    },
    wikipedia: "https://fr.wikipedia.org/wiki/V%C3%A9nus_(plan%C3%A8te)",
  },
  {
    id: "earth",
    name: "Terre",
    type: "planet",
    color: "#378ADD",
    desc: "La seule planète connue abritant la vie. Son champ magnétique la protège des vents solaires.",
    facts: {
      distance: "150M km du Soleil",
      rayon: "6 371 km",
      orbite: "365 jours",
    },
    radius: 0.5,
    texturePath: "/textures/8k_earth_daymap.jpg",
    roughness: 0.7,
    orbitR: 16,
    orbitColor: [0.25, 0.55, 1.0],
    speed: 0.5,
    speedKms: 29.8,
    rotSpeed: 1.0,
    inclination: 0,
    axialTilt: 23.44,
    nightTexturePath: "/textures/8k_earth_nightmap.jpg",
    hasMoon: true,
    atmosphere: { color: "100,180,255", size: 1.6 },
    clouds: {
      texture: "/textures/8k_earth_clouds.jpg",
      opacity: 0.6,
      speed: 0.8,
    },
    wikipedia: "https://fr.wikipedia.org/wiki/Terre",
  },
  {
    id: "mars",
    name: "Mars",
    type: "planet",
    color: "#D85A30",
    desc: "La Planète Rouge. Olympus Mons (22 km) est le plus grand volcan du système solaire.",
    facts: {
      distance: "228M km du Soleil",
      rayon: "3 389 km",
      orbite: "687 jours",
    },
    radius: 0.35,
    texturePath: "/textures/8k_mars.jpg",
    roughness: 0.75,
    orbitR: 22,
    orbitColor: [0.85, 0.3, 0.15],
    speed: 0.27,
    speedKms: 24.1,
    rotSpeed: 0.97,
    inclination: 1.85,
    axialTilt: 25.19,
    atmosphere: { color: "255,120,60", size: 1.3 },
    sim: {
      lunes: "Phobos et Deimos non représentées (trop petites à cette échelle)",
    },
    wikipedia: "https://fr.wikipedia.org/wiki/Mars_(plan%C3%A8te)",
  },
  {
    id: "asteroid-belt",
    name: "Ceinture d'astéroïdes",
    type: "belt",
    color: "#8a7a6a",
    desc: "Zone entre Mars et Jupiter contenant des millions de corps rocheux, vestige de la formation du système solaire.",
    facts: {
      distance: "300–500M km du Soleil",
      objets: "~1,1 million d'astéroïdes",
      largeur: "~225 millions km",
    },
    atmosphere: null,
    sim: {
      instances: "2 000 corps sur ~1,1 million réels",
      tailles: "Exagérées pour la visibilité",
    },
    wikipedia:
      "https://fr.wikipedia.org/wiki/Ceinture_d%27ast%C3%A9ro%C3%AFdes",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    type: "planet",
    color: "#EF9F27",
    desc: "La plus grande planète, 11× le diamètre terrestre. Sa Grande Tache Rouge est une tempête vieille de 350 ans.",
    facts: {
      distance: "778M km du Soleil",
      rayon: "69 911 km",
      orbite: "12 ans",
    },
    radius: 2.2,
    texturePath: "/textures/8k_jupiter.jpg",
    roughness: 0.5,
    orbitR: 32,
    orbitColor: [0.85, 0.65, 0.3],
    speed: 0.11,
    speedKms: 13.1,
    rotSpeed: 2.42,
    inclination: 1.3,
    axialTilt: 3.13,
    atmosphere: { color: "220,180,120", size: 6.2 },
    sim: {
      lunes: "4 lunes sur 95 représentées (Io, Europe, Ganymède, Callisto)",
    },
    wikipedia: "https://fr.wikipedia.org/wiki/Jupiter_(plan%C3%A8te)",
  },
  {
    id: "saturn",
    name: "Saturne",
    type: "planet",
    color: "#FAC775",
    desc: "Ses anneaux sont composés de glace et de roches. Sa densité est si faible qu'elle flotterait sur l'eau.",
    facts: {
      distance: "1,4 Md km du Soleil",
      rayon: "58 232 km",
      orbite: "29 ans",
    },
    radius: 1.9,
    texturePath: "/textures/8k_saturn.jpg",
    roughness: 0.45,
    orbitR: 42,
    orbitColor: [0.95, 0.85, 0.5],
    speed: 0.076,
    speedKms: 9.7,
    rotSpeed: 2.24,
    inclination: 2.49,
    axialTilt: 26.73,
    rings: true,
    ringsInnerRatio: 1.24, // inner = radius × 1.24
    ringsOuterRatio: 2.26, // outer = radius × 2.26
    atmosphere: { color: "210,180,140", size: 5.3 },
    sim: {
      lunes: "Titan uniquement sur 146 lunes",
      anneaux: "Structure simplifiée en texture unique",
    },
    wikipedia: "https://fr.wikipedia.org/wiki/Saturne_(plan%C3%A8te)",
  },
  {
    id: "uranus",
    name: "Uranus",
    type: "planet",
    color: "#9FE1CB",
    desc: "Tourne sur le côté avec une inclinaison de 98°. Découverte par William Herschel en 1781.",
    facts: {
      distance: "2,9 Md km du Soleil",
      rayon: "25 362 km",
      orbite: "84 ans",
    },
    radius: 1.1,
    texturePath: "/textures/2k_uranus.jpg",
    roughness: 0.4,
    orbitR: 54,
    orbitColor: [0.35, 0.85, 0.8],
    speed: 0.038,
    speedKms: 6.8,
    rotSpeed: -1.39,
    inclination: 0.77,
    axialTilt: 97.77,
    atmosphere: { color: "150,220,210", size: 3.3 },
    uranusRings: true,
    sim: {
      anneaux: "13 anneaux procéduraux (approximation)",
      lunes: "Non représentées",
    },
    wikipedia: "https://fr.wikipedia.org/wiki/Uranus_(plan%C3%A8te)",
  },
  {
    id: "neptune",
    name: "Neptune",
    type: "planet",
    color: "#5b8ff9",
    desc: "Vents jusqu'à 2 100 km/h. Découverte en 1846 par calcul mathématique avant toute observation.",
    facts: {
      distance: "4,5 Md km du Soleil",
      rayon: "24 622 km",
      orbite: "165 ans",
    },
    radius: 1.0,
    texturePath: "/textures/2k_neptune.jpg",
    roughness: 0.4,
    orbitR: 66,
    orbitColor: [0.15, 0.35, 0.9],
    speed: 0.019,
    speedKms: 5.4,
    rotSpeed: 1.49,
    inclination: 1.77,
    axialTilt: 28.32,
    atmosphere: { color: "80,120,255", size: 3.0 },
    sim: {
      lunes: "Triton uniquement sur 16 lunes",
    },
    wikipedia: "https://fr.wikipedia.org/wiki/Neptune_(plan%C3%A8te)",
  },
  {
    id: "moon",
    name: "Lune",
    type: "satellite",
    color: "#c8d0e8",
    desc: "Seul satellite naturel de la Terre. Stabilise l'axe de rotation terrestre et crée les marées.",
    facts: {
      distance: "384 400 km de la Terre",
      rayon: "1 737 km",
      orbite: "27 jours",
    },
    radius: 0.14,
    texturePath: "/textures/8k_moon.jpg",
    roughness: 0.75,
    orbitR: 1.1,
    orbitalSpeed: 6,
    rotSpeed: 6,
    speedKms: 1.0,
    parentId: "earth",
    atmosphere: null,
    wikipedia: "https://fr.wikipedia.org/wiki/Lune",
  },
  {
    id: "pluto",
    name: "Pluton",
    type: "dwarf",
    color: "#c4a882",
    desc: "Déclassée en planète naine en 2006. Possède 5 lunes dont Charon, presque aussi grande qu'elle.",
    facts: {
      distance: "5,9 Md km du Soleil",
      rayon: "1 188 km",
      orbite: "248 ans",
    },
    radius: 0.09,
    texturePath: "/textures/4k_pluto.jpg",
    roughness: 0.9,
    orbitR: 80,
    orbitColor: [0.6, 0.5, 0.45],
    speed: 0.008,
    speedKms: 4.7,
    rotSpeed: -0.16,
    inclination: 17.14,
    axialTilt: 122.5,
    atmosphere: null,
    sim: {
      taille: "Exagérée pour la visibilité à l'échelle du système",
    },
    wikipedia: "https://fr.wikipedia.org/wiki/Pluton_(plan%C3%A8te_naine)",
  },
  {
    id: "eris",
    name: "Éris",
    type: "dwarf",
    color: "#c8c4c0",
    desc: "Plus massive que Pluton, sa découverte en 2005 a conduit à redéfinir la notion de planète.",
    facts: {
      distance: "~10 Md km du Soleil",
      rayon: "1 163 km",
      orbite: "559 ans",
    },
    radius: 0.085,
    texturePath: "/textures/4k_eris.jpg",
    roughness: 0.95,
    orbitR: 96,
    orbitColor: [0.5, 0.5, 0.5],
    speed: 0.004,
    speedKms: 3.4,
    rotSpeed: 0.2,
    inclination: 44.04,
    axialTilt: 78.3,
    atmosphere: null,
    sim: {
      taille: "Exagérée pour la visibilité à l'échelle du système",
    },
    wikipedia: "https://fr.wikipedia.org/wiki/%C3%89ris_(plan%C3%A8te_naine)",
  },
  {
    id: "makemake",
    name: "Makemake",
    type: "dwarf",
    color: "#b87a5a",
    desc: "Troisième plus grande planète naine connue. Pas d'atmosphère détectée, surface de méthane gelé.",
    facts: {
      distance: "~6,8 Md km du Soleil",
      rayon: "715 km",
      orbite: "305 ans",
    },
    radius: 0.07,
    texturePath: "/textures/4k_makemake.jpg",
    roughness: 0.95,
    orbitR: 88,
    orbitColor: [0.55, 0.45, 0.4],
    speed: 0.006,
    speedKms: 4.4,
    rotSpeed: 0.3,
    inclination: 28.96,
    axialTilt: 29.0,
    atmosphere: null,
    sim: {
      taille: "Exagérée pour la visibilité à l'échelle du système",
    },
    wikipedia:
      "https://fr.wikipedia.org/wiki/Mak%C3%A9mak%C3%A9_(plan%C3%A8te_naine)",
  },
  {
    id: "haumea",
    name: "Hauméa",
    type: "dwarf",
    color: "#d0ccc8",
    desc: "Forme ellipsoïdale unique due à sa rotation très rapide (4h). Possède deux petites lunes.",
    facts: {
      distance: "~6,4 Md km du Soleil",
      rayon: "780 km (axe long)",
      orbite: "284 ans",
    },
    radius: 0.065,
    texturePath: "/textures/4k_haumea.jpg",
    roughness: 0.9,
    orbitR: 84,
    orbitColor: [0.5, 0.5, 0.52],
    speed: 0.0055,
    speedKms: 4.5,
    rotSpeed: 6.0,
    inclination: 28.19,
    axialTilt: 126.4,
    atmosphere: null,
    sim: {
      taille: "Exagérée pour la visibilité à l'échelle du système",
    },
    wikipedia: "https://fr.wikipedia.org/wiki/Haumea_(plan%C3%A8te_naine)",
  },
];

// #endregion

// #region ── Labels par type (sidebar + tooltip) ───────────────────────────────

export const TYPE_LABELS = {
  star: { label: "Étoiles", color: "#F9CB42" },
  planet: { label: "Planètes", color: "#5b8ff9" },
  satellite: { label: "Satellites", color: "#5DCAA5" },
  belt: { label: "Ceintures", color: "#8a7a6a" },
  dwarf: { label: "Planètes naines", color: "#a0889a" },
  probe: { label: "Sondes", color: "#F5C4B3" },
};

// #endregion
