// data.js — source de vérité unique pour tous les objets spatiaux

export const OBJECTS = [
  {
    // ── Identification ──
    id: "sun",
    name: "Soleil",
    type: "star",
    // ── UI ──
    color: "#F9CB42",
    desc: "Notre étoile, âgée de 4,6 milliards d'années. Elle représente 99,8 % de la masse du système solaire.",
    facts: {
      distance: "Centre",
      rayon: "696 340 km",
      type: "Naine jaune (G2V)",
    },
    // ── 3D ──
    radius: 2.5,
    texturePath: "/textures/8k_sun.jpg",
    emissive: true,
    rotSpeed: 0.037,
    atmosphere: null,
  },
  {
    id: "mercury",
    name: "Mercure",
    type: "planet",
    color: "#b4b2a9",
    desc: "La plus petite planète du système solaire. Sans atmosphère protectrice, les températures varient de -180°C à 430°C.",
    facts: {
      distance: "77M km du Soleil",
      rayon: "2 439 km",
      orbite: "88 jours",
    },
    radius: 0.25,
    texturePath: "/textures/8k_mercury.jpg",
    roughness: 1,
    orbitR: 8,
    speed: 0.8,
    rotSpeed: 0.017,
    inclination: 7.0,
    axialTilt: 0.03,
    atmosphere: null,
  },
  {
    id: "venus",
    name: "Vénus",
    type: "planet",
    color: "#F0997B",
    desc: "La planète la plus chaude (465°C). Tourne à l'envers et une journée vénusienne dure plus longtemps qu'une année.",
    facts: {
      distance: "108M km du Soleil",
      rayon: "6 051 km",
      orbite: "225 jours",
    },
    radius: 0.48,
    texturePath: "/textures/8k_venus_surface.jpg",
    roughness: 0.95,
    orbitR: 12,
    speed: 0.62,
    rotSpeed: -0.004,
    inclination: 3.4,
    axialTilt: 177.4,
    atmosphere: { color: "255,200,100", size: 1.8 },
    clouds: {
      texture: "/textures/4k_venus_atmosphere.jpg",
      opacity: 0.5,
      speed: -0.3,
    },
  },
  {
    id: "earth",
    name: "Terre",
    type: "planet",
    color: "#378ADD",
    desc: "La seule planète connue abritant la vie. Son champ magnétique la protège des vents solaires.",
    facts: {
      distance: "150M km du Soleil",
      rayon: "6 371 km",
      orbite: "365 jours",
    },
    radius: 0.5,
    texturePath: "/textures/8k_earth_daymap.jpg",
    roughness: 0.7,
    orbitR: 16,
    speed: 0.5,
    rotSpeed: 1.0,
    inclination: 0,
    axialTilt: 23.44,
    nightTexturePath: "/textures/8k_earth_nightmap.jpg",
    hasMoon: true,
    atmosphere: { color: "100,180,255", size: 1.6 },
    clouds: {
      texture: "/textures/8k_earth_clouds.jpg",
      opacity: 0.6,
      speed: 0.8,
    },
  },
  {
    id: "mars",
    name: "Mars",
    type: "planet",
    color: "#D85A30",
    desc: "La Planète Rouge. Olympus Mons (22 km) est le plus grand volcan du système solaire.",
    facts: {
      distance: "228M km du Soleil",
      rayon: "3 389 km",
      orbite: "687 jours",
    },
    radius: 0.35,
    texturePath: "/textures/8k_mars.jpg",
    roughness: 0.75,
    orbitR: 22,
    speed: 0.27,
    rotSpeed: 0.97,
    inclination: 1.85,
    axialTilt: 25.19,
    atmosphere: { color: "255,120,60", size: 1.3 },
  },
  {
    id: "jupiter",
    name: "Jupiter",
    type: "planet",
    color: "#EF9F27",
    desc: "La plus grande planète, 11× le diamètre terrestre. Sa Grande Tache Rouge est une tempête vieille de 350 ans.",
    facts: {
      distance: "778M km du Soleil",
      rayon: "69 911 km",
      orbite: "12 ans",
    },
    radius: 1.4,
    texturePath: "/textures/8k_jupiter.jpg",
    roughness: 0.5,
    orbitR: 32,
    speed: 0.11,
    rotSpeed: 2.42,
    inclination: 1.3,
    axialTilt: 3.13,
    atmosphere: { color: "220,180,120", size: 2.2 },
  },
  {
    id: "saturn",
    name: "Saturne",
    type: "planet",
    color: "#FAC775",
    desc: "Ses anneaux sont composés de glace et de roches. Sa densité est si faible qu'elle flotterait sur l'eau.",
    facts: {
      distance: "1,4 Md km du Soleil",
      rayon: "58 232 km",
      orbite: "29 ans",
    },
    radius: 1.15,
    texturePath: "/textures/8k_saturn.jpg",
    roughness: 0.45,
    orbitR: 42,
    speed: 0.076,
    rotSpeed: 2.24,
    inclination: 2.49,
    axialTilt: 26.73,
    rings: true,
    atmosphere: { color: "210,180,140", size: 2.0 },
  },
  {
    id: "uranus",
    name: "Uranus",
    type: "planet",
    color: "#9FE1CB",
    desc: "Tourne sur le côté avec une inclinaison de 98°. Découverte par William Herschel en 1781.",
    facts: {
      distance: "2,9 Md km du Soleil",
      rayon: "25 362 km",
      orbite: "84 ans",
    },
    radius: 0.75,
    texturePath: "/textures/2k_uranus.jpg",
    roughness: 0.4,
    orbitR: 54,
    speed: 0.038,
    rotSpeed: -1.39,
    inclination: 0.77,
    axialTilt: 97.77,
    atmosphere: { color: "150,220,210", size: 1.8 },
  },
  {
    id: "neptune",
    name: "Neptune",
    type: "planet",
    color: "#5b8ff9",
    desc: "Vents jusqu'à 2 100 km/h. Découverte en 1846 par calcul mathématique avant toute observation.",
    facts: {
      distance: "4,5 Md km du Soleil",
      rayon: "24 622 km",
      orbite: "165 ans",
    },
    radius: 0.7,
    texturePath: "/textures/2k_neptune.jpg",
    roughness: 0.4,
    orbitR: 66,
    speed: 0.019,
    rotSpeed: 1.49,
    inclination: 1.77,
    axialTilt: 28.32,
    atmosphere: { color: "80,120,255", size: 1.8 },
  },
  {
    id: "moon",
    name: "Lune",
    type: "satellite",
    color: "#c8d0e8",
    desc: "Seul satellite naturel de la Terre. Stabilise l'axe de rotation terrestre et crée les marées.",
    facts: {
      distance: "384 400 km de la Terre",
      rayon: "1 737 km",
      orbite: "27 jours",
    },
    radius: 0.14,
    texturePath: "/textures/8k_moon.jpg",
    roughness: 0.75,
    orbitR: 1.1,
    orbitalSpeed: 6,
    rotSpeed: 6,
    parentId: "earth",
    atmosphere: null,
  },
];

// Regroupement par type pour la sidebar
export const TYPE_LABELS = {
  star: { label: "Étoiles", color: "#F9CB42" },
  planet: { label: "Planètes", color: "#5b8ff9" },
  satellite: { label: "Satellites", color: "#5DCAA5" },
  probe: { label: "Sondes", color: "#F5C4B3" },
};
